<main class="history">
    <div class="container--main">
        <h1>Le Commando Kieffer</h1>
        <blockquote>
            Le 1er Bataillon de Fusilers Marins Commandos <br>
            par Lardennois (2005)
        </blockquote>

        <p>Le Capitaine de corvette Philippe Kieffer est né à Haïti le 24 octobre 1899. Diplômé de l’école H.E.C, il est directeur de banque aux U.S.A lorsque la guerre menace nos frontières. Malgré son âge, il s’engage comme volontaire dans la Marine le 10 septembre 1939.</p>
        <p>Le Lieutenant de Vaisseau Kieffer est Officier de Réserve Interprète et du Chiffre. Après la défaite de Dunkerque, il rejoint le Royaume-Uni le 19 juin 1940 et répondant à l’appel du Général de Gaulle. Il s’engage des les Forces Navales Françaises Libres le 1er juillet 1940. Son numéro matricule est le 13 FNFL 40.</p>
        <p>Affecté au chiffre, le Lieutenant de Vaisseau Kieffer trouve la vie monotone à bord du cuirassé Amiral Courbet, bâtiment ancré au fond de la rade de Portsmouth servant de base anti-aérienne et hors d’usage pour le service en mer. Le Commandant veut affronter l’ennemi sur les champs de bataille.</p>
        <p>Début mars 1941, alors qu’il se trouve dans le train qui le conduit de Southampton à Londres, le Lt de Vaisseau Kieffer prend connaissance de l’exploit du N° 4 Commando lors du raid sur les îles Lofoten (Norvège). Le mot « Commando » agit comme un révélateur et l’obsède. Une idée germe dans sa tête : « Pourquoi ne pas créer une force française semblable à celle qui vient d’effectuer ce raid ? Une force capable de frapper l’ennemi sur le sol de la patrie. » Il fallait créer un Commando français.</p>
        <p>Après s’être rendu à la caserne Surcouf pour vainement tenter de convaincre ses supérieurs, le Lt de Vaisseau Kieffer parvient à être reçu par l’Amiral Muselier. Ce dernier accepte l'idée mais semble sceptique quant à la décision des autorités militaires Britanniques. Fin mars 1941, KIEFFER est reçu par le Général Haydon au Q.G des Forces Combinées à Richmond Terrace à qui il présente son projet. L'autorisation de la création d'un commando français appelé à servir dans les troupes britanniques lui parvient 15 jours plus tard.</p>
        <p>En avril, une quinzaine de volontaires sont recrutés par le Lt Vourch. Malgré l'absence d'armes et de munitions, l'entraînement physique intensif commence immédiatement au camp de Camberley. Ce premier groupe prend le nom de 1ère Compagnie de Fusiliers Marins. Les moyens et les hommes arrivent, l'effectif passe à une quarantaine de personnels. C'est là que prend racine cette profonde camaraderie et l'esprit de corps qui unit ces hommes encore aujourd'hui. La compagnie est invitée à Eastney Barracks chez les Royal Marines puis affectée au numéro 2 Commando après un stage à Achnaccary fin mai 1942.</p>
        <p>Le 19 août 1942, lors du raid de Dieppe a lieu la première participation de 15 commandos de la compagnie. Quelques semaines après le raid de Dieppe les hommes recevront le béret vert des commandos. A partir de cette date, les volontaires affluent pour être recrutés dans la 1ère Compagnie de Fusiliers Marins qui ne prendra officiellement le nom de Première Compagnie Fusiliers Marins Commandos que le 12 novembre 1942 (note 952 F.N.F.L.).</p>
        <p>Pour former une nouvelle Troop, le Lt Trepel recrute soixante-quinze Fusiliers Marins arrivés du Liban avec le Lt Lofi après la dissolution du 2ème Bataillon, une vingtaine d'évadés de France et quelques éléments venus d'Afrique du Nord.</p>
        <p>Pour avoir l'honneur de servir dans cette Compagnie, chaque candidat doit obtenir son béret vert qui sera porté « à l'Anglaise » après une formation au redoutable centre d'instruction commando d'Achnaccary en Ecosse.</p>
        <p>A l'automne 1943, la compagnie se renforce et devient le 1er Bataillon de Fusiliers Marins Commandos (1er B.F.M.C) qui est fort de Trois Troops la N°1, la N°8 et la Troop d’Appui (K-Guns). A partir de novembre 1943, le bataillon installé sur les côtes sud de l'Angleterre, effectue un grand nombre de missions de reconnaissance, de raids et de sondage sur les côtes françaises, belges et hollandaises. Des missions d'attaque pour tâter les réactions ennemies, de destruction de radar, de kidnapping de soldats allemands sont aussi effectuées après de très minutieuses répétitions et une imagination sans cesse renouvelée des détails. Le Bataillon participe à des missions de renseignement sur Graveline où le Maître Wallerand, allant jusqu'au bout de sa volonté, meurt à quelques mètres de la vedette qu'il doit rejoindre au retour de sa mission. Le raid de Jersey dans la nuit du 4 au 25 décembre 1943 où le Sous-Lieutenant Hulot prend le commandement à la mort de son chef, le Capitaine Hayton, dont il ramène le corps. Scheveningen en Hollande en février 1944 où le Capitaine Trepel ses cinq commandos ( le Second Maître Agnerre, les commandos Devillers, Cabanella, Guy et Rivière) sont portés disparus lors d'une mission de reconnaissance d'un point de débarquement pour des agents alliés. Leur mort est restée un mystère car aucun coup de feu n'a été entendu par les marins qui attendaient le groupe à bord du dinghy qui les avait amenés. Les corps retrouvés ne portaient aucune blessure.</p>
        <p>En mars 1944, tous les raids sont suspendus. Les commandos français sont intégrés au 4ème commando Anglais pour la préparation du débarquement.</p>
        <p>En mai 1944, le Bataillon reçoit son propre insigne de béret qui est un écu de bronze chargé du brick de l’aventure et barré du poignard des commandos avec dans le coin gauche la croix de Lorraine et souligné d’une banderole portant l’inscription -1er Bon F.M.Commando - Le dessin est dû à un membre du Commando, le Caporal Maurice Chauvet.</p>
        <p>La 1er Bataillon, surnommé le Commando Kieffer, aura l’honneur suprême de débarquer le premier en France le Jour J. Le 5 juin en fin d'après-midi, le Commando embarque sur les L.C.I's, destination les côtes normandes de la mère patrie.</p>
        <p>Promu Capitaine de Corvette à la veille du débarquement, le commandant Kieffer débarque en Normandie à la tête de ses 177 hommes du 1er Bataillon de Fusiliers Marins Commandos le 06 juin 1944. Ils débarquent sur la plage Sword à Colleville-Montgomery au lieu dit la brêche. Malgré des pertes significatives, ils accomplissent leurs mission. Ils s’emparent d’une pièce de 50 mm encuvée qui avait mis à mal la péniche LCI 523 (1ère Troop), puis de blockhaus de l'ex-Casino de Riva-Bella devenu poste de commandement allemand. Le sous-lieutenant Hubert, un des plus jeunes officiers, est tué lors de l'attaque.</p>
        <p>Le Commando s'enfonce ensuite dans les terres par Colleville et St Aubin d'arquenay pour faire jonction à Pegasus Bridge à Bénouville avec les Airborne britanniques de la 6e DAP. Ils y arrivent vers 16h30. Kieffer sera blessé deux fois ce jour-là. Au soir du 6 juin, le 1er B.F.M.C aura perdu presque 25% de ses effectifs. Il occupe alors les lisières du Plain vers 20h00. Le 10 juin, le commando repousse une violente attaque des Allemands. Ce jour là, le Commandant Kieffer est évacué suite aux blessures reçues le 6 juin. Le Lt Lofi prendra le commandement jusqu'au 13 juillet, date de retour du Commandant.</p>
        <p>Au cours de la dure campagne de Normandie, les Commandos poursuivront par Bavent. Le Pont l'Evèque est traversé le 24 août. Ils restèrent en première ligne (secteur Le Plain - Amfreville) et combattirent jusqu’au 27 août 1944 date à laquelle ils entrent à Beuzeville qui n'est plus occupé. Ils y cantonneront jusqu'au 6 septembre, date à laquelle ils regagneront le camp de Petworth (West Sussex). Pendant ce temps Paris est libéré.</p>
        <p>Après leur retour en Angleterre, pour mise au repos et reconditionnement, le 4ème commando, unité de 500 hommes auquel appartient le 1er B.F.M.C, est intégré à la 1ère armée canadienne en Belgique. Le 1er novembre 1944, une mission difficile se présente: la prise de l'ile de Walcheren afin d'ouvrir le canal d'accès au port d'Anvers. La ville de Flessingue est le premier objectif. En deux jours la ville est prise. Pour l'ennemi, le bilan est sévère : 500 tués ou blessés et plus de 1000 prisonnniers. Le commandant suprême des forces alliées devait déclarer qu'il considérait cette opération comme la plus brave et la plus audacieuse de cette guerre. Suivent ensuite 3 raids sur l'ile de Schouwen et deux dernières batailles à Wessel et Minden avant la signature de l'armistice. Les commandos rentrent alors en Angleterre. Durant cette guerre, le bataillon de Fusiliers Marins aura été cinq fois cité à l'ordre de l'Armée et aura reçu les fourragères de la croix de guerre et de la médaille militaire.</p>
        <p>Le 1er juillet 1946, le N°4 commando est dissout au camp de Bir-Hakeim, près de Portsmouth mais le 1er Bataillon de Fusiliers Marins Commandos continue d'exister et porte encore fièrement aujourd’hui les armes de la France.</p>
    
        <div class="bottom-txt">
            <h2>Les 177 du Jour J.</h2>
            <p>Commandant : Major Philippe KIEFFER</p>
            <h4>Quartier Général</h4>        
            <p>Capitaine R de Naurois (Aumônier) - Cpl. M. Chauvet - L/Cpl. F. Devager - Cpl. O.Gouriou Sgt. G.Hattu</p>
            <h4>Unité médicale</h4>        
            <p>Médecin Capitaine Lion - L/Cpl. G. Bolloré - L/Sgt. O. Bouarfa</p>
            <h4>Opérateurs Radio</h4>        
            <p>L/Cpl. E. Bougrain - Sgt. P. Briat - L/Cpl. J. Couturier - L/Cpl. A. Denereaz - Cpl. R. Gadou - L/Cpl. L.Godard - Pvt. R.Goujon - L/Cpl. M. Legrand - Cpl. H. Richemont</p>
            <h4>Transport</h4>        
            <p>Sgt. H. Nassau de Warigny - L/Sgt. G. Paillet - Cpl. P. Richen - Cpl. R. Roux</p>

            <h3>Troop 1</h3>
            <p>Lieutenant Guy Vourch</p>
            <p>L/Cpl. A. Allain - Cpl. A. Autin - L/Cpl. L. Bégot - L/Cpl. B. Beux - Sgt. P. Boccador - L/Cpl. G. Bouchard - L/Cpl. J. Bouilly - L/Cpl. A. Bourret - Sgt. R. Bucher - Cpl. L. Cabellan - Cpl. Laurent Casalonga - Pvt. M. Corbin - L/Cpl. R. Dechambou - L/Cpl. M. Derrien - Sgt. R. Dumanoir - L/Cpl. G. Fagou - W.O.1 H. Faure - L/Cpl. R. Flesch - L/Cpl. M. Fromager - L/Cpl. R. Gabriel - Cpl. F. Garrabos - Cpl. Zivohlava - L/Cpl. G.Guillou - Sgt. J.Horny - Cpl. J. Kermarec - Cpl. M. Lahouze - Sgt. L. Lanternier - Sgt. Major A. Lardennois - Sgt. M. Laventure - Cpl. J. Le Goff - L/Cpl. R. Le Morvan - L/Sgt. J. Le Naour - L/Cpl. R. Leostic - Cpl. R. Lossec - L/Cpl. R. Madrias - Cpl. F. Magy - L/Cpl. J. Masson - 2/Lieut. J. Mazeas - L/Cpl. Y. Meudal - Sgt. G. de Montlaur - L/Cpl. A. Neven - Pvt. J. Neven - L/Cpl. J. Nicot - L/Cpl. M. Niel - L/Cpl. J. Pérone - L/Cpl. R. Piauge - L/Cpl. G. Picou - Lieut. J. Pinelli - L/Cpl. N. Poli - L/Cpl. Y. Quentric - Cpl. P. Quere - L/Cpl. M. Raulin - L/Cpl. E. Renault - L/Cpl. P. Roîlin - Cpl. G. Ropert - Pvt. J. Rousseau - Cpl. Y. Ruppé - L/Cpl J.Salaum - Cpl. G. Scherer - Cpl. J. Simon - Cpl. P. Tanniou - Cpl. P. Vinat - L/Cpl. M. Vincent –</p>

            <h3>Troop 8</h3>
            <p>Lieutenant Alex Lofi</p>
            <p>L/Cpl. A. Archieri - 2/Lieut. A. Bagot - L/Cpl. N. Ballaro - Sgt. M. Barbe - Cpl. A. Bernard - Cpl. J. Biestro - Pvt. R. Boulanger - L/Cpl. G. Briand - L/Cpl. M. Caille - Cpl. J. Cevoz -Mami - Sgt. Major P. Chausse - Cpl. P. Chouteau - L/Cpl. G. Coppin - L/Sgt. R. Croizer - L/Sgt. H. Dorfsman - L/Cpl. R. Ducasse - L/Cpl. A. Dupont - Cpl. P. Ernault - Cpl. A. Foliot - L/Cpl. R. Fougere - Cpl. L. Fourer - L/Cpl. J. Galton - Cpl. M. Gannat - Cpl. L.Gautier - L/Cpl. H.Gicquel - L/Cpl. A.Grail - L/Cpl. F.Grispin - Pvt. P.Guidicelli - Cpl. J.Guilcher - L/Cpl. E.Guinebault - L/Cpl. J.Guyader - Sgt. J.Hourcourigaray - 2/Lieut. L.Hulot - L/Sgt. R.Jovenin - L/Cpl. A. Jung - Sgt. Major F. Klopfenstein - L/Cpl. G. Laot - Sgt. Major M. Lavezzi - Cpl. H. Lechaponnier - L/Cpl. M. Le Floch - L/Cpl. B. Le Reste - L/Cpl. A. Le Rigoleur - Pvt. R. Lesca - Cpl. J. Letang - Sgt. M. Logeais - Pvt. A. Maler - Sgt. P. Mariaccia - L/Cpl. R. Massin - Sgt. G. Messanot - Pvt. R. Moguerou - L/Cpl. J. Montean - Cpl. J. Morel - Pvt. R. Ohliger - L/Cpl. J. Plancher - L/Cpl. L. Prévost - Pvt Rabouhans Raymond - L/Cpl. J. Reiffers - L/Cpl. M. Riveau - Sgt. R. Roelandt - L/Cpl. M. Rougier - Cpl. M. Rouxel - Sgt. J. Senée - L/Cpl. R. Strina - Sgt. M. Thubé - L/Cpl. E. Troyard - Pvt. F. Vourch - L/Cpl. H. Wallen</p>

            <h3>Troop K-Gun</h3>
            <p>Lieutenant Pierre Amaury</p>
            <p>Pvt. F. Andriot - Sgt. A. Cartier - L/Sgt. G. Coste - L/Cpl. L. Danson - Cpl. P. Demonet - Pvt. R.Gersel - Pvt. M.Gery - Pvt. F.Guezennec - Pvt. E.Guy - 2/Lieut. A.Hubert - L/Cpl. M. Labas -Cpl. J. Le Bris - Cpl. J.Lemoigne - L/Cpl. J. Monceaux - Pvt. J. Guivarch - Pvt. J. Peters - Cpl. J. Piriou - Pvt. J. Priez - Pvt. M. Ravel - Pvt. R. Rossey - Sgt. R. Saerens -L/Cpl. C. Valentin -</p>
        </div>
    </div>
</main>